#!/usr/bin/env python3
"""Generates supabase/seed.sql: categories, styles, and 30-50 demo salons
in and around Braamfontein/Johannesburg, per docs/consumer-flow.md step 1
of the build order ("seed 30-50 salons in one area").

Deterministic: uuid5 off stable names, random.seed fixed, so re-running
produces byte-identical output. Run: python3 scripts/generate_seed.py
"""
import random
import uuid

random.seed(42)
NAMESPACE = uuid.UUID("6f6b2f1a-0000-4000-8000-000000000000")


def uid(*parts: str) -> str:
    return str(uuid.uuid5(NAMESPACE, "|".join(parts)))


def sql_str(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


CATEGORIES = [
    ("braids", "Braids", 1),
    ("installs_weaves", "Installs/Weaves", 2),
    ("nails", "Nails", 3),
    ("lashes", "Lashes", 4),
    ("makeup", "Makeup", 5),
    ("barber", "Barber", 6),
]

# (category_slug, name, description, base_price_rand, duration_minutes, hair_relevant)
STYLES = [
    ("braids", "Knotless box braids, mid-back", "Tension-free knotless braids to mid-back length.", 650, 360, True),
    ("braids", "Cornrows, straight back", "Classic straight-back cornrows.", 250, 120, False),
    ("braids", "Feed-in braids, shoulder length", "Feed-in braids finishing at shoulder length.", 450, 240, True),
    ("installs_weaves", "Bone straight weave install", "Full sew-in with bone straight bundles.", 900, 240, True),
    ("installs_weaves", "Body wave closure install", "Closure install with body wave texture.", 1100, 270, True),
    ("installs_weaves", "Frontal install with baby hair", "13x4 frontal install, baby hair laid and melted.", 1600, 300, True),
    ("nails", "Gel overlay, natural nails", "Gel overlay on natural nail length.", 280, 60, False),
    ("nails", "Acrylic full set, almond", "Full acrylic set shaped almond.", 380, 90, False),
    ("nails", "Nail art, 2 accent nails", "Full set plus hand-painted accent nails.", 450, 105, False),
    ("lashes", "Classic lash extensions", "One extension per natural lash, natural look.", 350, 90, False),
    ("lashes", "Hybrid lash extensions", "Mix of classic and volume fans.", 450, 105, False),
    ("lashes", "Volume lash extensions", "Full volume fans for a dramatic look.", 550, 120, False),
    ("makeup", "Everyday glam makeup", "Soft glam for everyday wear or events.", 400, 60, False),
    ("makeup", "Bridal makeup trial", "Full trial run ahead of the big day.", 800, 90, False),
    ("makeup", "Full glam + lashes", "Full glam application with strip lashes included.", 600, 75, False),
    ("barber", "Skin fade + line up", "Skin fade with a crisp line up.", 150, 45, False),
    ("barber", "Afro shape-up", "Afro shape and shape-up, no fade.", 120, 30, False),
    ("barber", "Beard trim + hot towel", "Beard shape-up finished with a hot towel.", 100, 30, False),
]

# (suburb, lat, lng)
SUBURBS = [
    ("Braamfontein", -26.1929, 28.0305),
    ("Melville", -26.1751, 28.0034),
    ("Parktown", -26.1858, 28.0423),
    ("Rosebank", -26.1467, 28.0436),
    ("Sandton", -26.1076, 28.0567),
    ("Randburg", -26.0939, 27.9769),
    ("Auckland Park", -26.1809, 27.9989),
    ("Yeoville", -26.1834, 28.0578),
    ("Observatory", -26.1697, 28.0716),
    ("Orlando, Soweto", -26.2485, 27.8540),
    ("Kensington", -26.1934, 28.0959),
    ("Norwood", -26.1553, 28.0748),
]

NAME_PREFIXES = [
    "Zanele's", "Thando's", "Naledi", "Lerato's", "Boitumelo", "Palesa's",
    "Refilwe", "Nomvula's", "Amahle", "Kgomotso's", "Ayanda", "Busisiwe's",
    "Karabo", "Precious", "Sibongile's", "Tumi's", "Mbali", "Nokuthula's",
    "Lindiwe", "Ntombi's", "Rethabile", "Dineo's", "Onthatile", "Keitumetse's",
    "Fikile", "Thandiwe's", "Sisanda", "Mmabatho's", "Andiswa", "Nozipho's",
    "Lesedi", "Puleng's", "Aphiwe", "Bontle's", "Cebisa",
]

CATEGORY_SUFFIX = {
    "braids": ["Braids", "Braid Bar", "Braiding Studio"],
    "installs_weaves": ["Hair Lounge", "Weave Studio", "Hair Studio"],
    "nails": ["Nail Bar", "Nails", "Nail Studio"],
    "lashes": ["Lash Studio", "Lash Bar", "Beauty Lounge"],
    "makeup": ["Makeup Studio", "Glam Room", "Beauty Bar"],
    "barber": ["Barbershop", "Barber Lounge", "Cuts"],
}

NUM_SALONS = 36
lines = []

lines.append("-- Generated by scripts/generate_seed.py -- do not hand-edit, regenerate instead.")
lines.append("")

# categories
lines.append("insert into categories (slug, label, sort_order) values")
lines.append(",\n".join(
    f"  ({sql_str(slug)}, {sql_str(label)}, {order})" for slug, label, order in CATEGORIES
) + ";")
lines.append("")

# styles
style_ids = {}
lines.append("insert into styles (id, category_slug, name, description, cover_photo_url) values")
style_rows = []
for slug, name, desc, _price, _dur, _hair in STYLES:
    style_id = uid("style", name)
    style_ids[name] = style_id
    photo_seed = name.lower().replace(" ", "-").replace(",", "")
    photo_url = f"https://picsum.photos/seed/style-{photo_seed}/800/1000"
    style_rows.append(
        f"  ({sql_str(style_id)}, {sql_str(slug)}, {sql_str(name)}, {sql_str(desc)}, {sql_str(photo_url)})"
    )
lines.append(",\n".join(style_rows) + ";")
lines.append("")

# salons
used_names = set()
salon_rows = []
service_rows = []
photo_rows = []

for i in range(NUM_SALONS):
    suburb, base_lat, base_lng = SUBURBS[i % len(SUBURBS)]
    # jitter within roughly 1.5km so distance queries have spread
    lat = base_lat + random.uniform(-0.012, 0.012)
    lng = base_lng + random.uniform(-0.012, 0.012)

    specialty_categories = random.sample(CATEGORIES, k=random.choice([1, 1, 2]))
    primary_slug = specialty_categories[0][0]

    while True:
        prefix = random.choice(NAME_PREFIXES)
        suffix = random.choice(CATEGORY_SUFFIX[primary_slug])
        name = f"{prefix} {suffix}"
        if name not in used_names:
            used_names.add(name)
            break

    salon_id = uid("salon", name)
    is_mobile = random.random() < 0.25
    is_verified = random.random() < 0.55
    is_claimed = random.random() < 0.2
    rating_avg = round(random.uniform(3.6, 5.0), 1)
    rating_count = random.randint(4, 180)
    avg_response = random.choice([15, 30, 45, 60, 90, 120])
    phone = f"+2782{random.randint(1000000, 9999999)}"
    address = f"{random.randint(1, 200)} {random.choice(['Jorissen', 'Juta', '4th', 'Main', '7th', 'De Beer', 'Kingsway', 'Empire'])} St"
    hours = (
        '{"mon_fri": "09:00-18:00", "sat": "08:00-16:00", "sun": "closed"}'
    )

    salon_rows.append(
        "  ("
        f"{sql_str(salon_id)}, {sql_str(name)}, {str(is_claimed).lower()}, "
        f"{str(is_verified).lower()}, {str(is_mobile).lower()}, {sql_str(phone)}, {sql_str(phone)}, "
        f"{sql_str(address)}, {sql_str(suburb)}, 'Johannesburg', "
        f"st_setsrid(st_makepoint({lng:.6f}, {lat:.6f}), 4326)::geography, "
        f"'{hours}'::jsonb, {avg_response}, {rating_avg}, {rating_count})"
    )

    photo_seed = name.lower().replace(" ", "-").replace("'", "")
    photo_rows.append(
        f"  ({sql_str(uid('photo', name, 'hero'))}, {sql_str(salon_id)}, null, "
        f"{sql_str(f'https://picsum.photos/seed/{photo_seed}-hero/900/1200')}, true, 0)"
    )
    for p in range(2):
        photo_rows.append(
            f"  ({sql_str(uid('photo', name, str(p)))}, {sql_str(salon_id)}, null, "
            f"{sql_str(f'https://picsum.photos/seed/{photo_seed}-{p}/900/1200')}, false, {p + 1})"
        )

    offered_styles = [
        s for s in STYLES if s[0] in {c[0] for c in specialty_categories}
    ]
    for style in random.sample(offered_styles, k=min(len(offered_styles), random.choice([2, 3, 4]))):
        slug, sname, _desc, base_price, base_dur, hair_relevant = style
        style_id = style_ids[sname]
        price_cents = int(base_price * random.uniform(0.85, 1.25)) * 100
        duration = int(base_dur * random.uniform(0.85, 1.15))
        hair_included = hair_relevant and random.random() < 0.5
        hair_delta = int(base_price * 0.15) * 100 if hair_relevant and not hair_included else 0
        service_rows.append(
            "  ("
            f"{sql_str(uid('service', name, sname))}, {sql_str(salon_id)}, {sql_str(style_id)}, "
            f"{price_cents}, {str(hair_included).lower()}, {hair_delta}, {duration}, true)"
        )

lines.append(
    "insert into salons (id, name, is_claimed, is_verified, is_mobile, phone, whatsapp, "
    "address_line, suburb, city, location, operating_hours, avg_response_minutes, "
    "rating_avg, rating_count) values"
)
lines.append(",\n".join(salon_rows) + ";")
lines.append("")

lines.append(
    "insert into salon_services (id, salon_id, style_id, price_cents, hair_included, "
    "hair_included_price_delta_cents, duration_minutes, is_active) values"
)
lines.append(",\n".join(service_rows) + ";")
lines.append("")

lines.append(
    "insert into salon_photos (id, salon_id, style_id, photo_url, is_hero, sort_order) values"
)
lines.append(",\n".join(photo_rows) + ";")
lines.append("")

with open("supabase/seed.sql", "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote supabase/seed.sql: {len(salon_rows)} salons, {len(service_rows)} services, {len(photo_rows)} photos")
